stages:
  - test
  - deploy

Build and test Rust code:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test

Publish crate:
  stage: deploy
  image: rustlang/rust:nightly
  script:
    - sh -c 'cargo login "${CARGO_TOKEN}" && cargo publish'
  only:
    - tags

